version: '2'
services:
  candidate:
    image: camiloribeiro/rest_shifter
    ports:
      - "9881:8080"
    volumes:
      - ./flavors/candidate:/root/.rest_shifter/flavors
    command: -s

  primary:
    image: camiloribeiro/rest_shifter
    ports:
      - "9882:8080"
    volumes:
      - ./flavors/primary:/root/.rest_shifter/flavors
    command: -s

  secondary:
    image: camiloribeiro/rest_shifter
    ports:
      - "9883:8080"
    volumes:
      - ./flavors/secondary:/root/.rest_shifter/flavors
    command: -s
